### ISSUE TITLE
Merge api-evidence and api-dispute and translate to Typescript

### ISSUE THREAD

**Issue by solomondefi-dev** [SolomonDefi/solomon-monorepo#221]
We're running into some difficulties with sharing code/fixtures, maintaining a separate build system/plugin, and getting some Ethereum-specific functionality working. Additionally, the other blockchains/layer 2 solutions under consideration (Arbitrum, Flow, etc) have much better support for Javascript than Python.

This issue should be broken up into implementation tasks before work starts. @apolkingg8 I considered your points about this refactor, it definitely will save time and effort in the long term.

#### Tasks
- [ ] Remove `api-evidence` and `api-dispute` from skaffold build
- [ ] Create `api` NestJS app with MikroORM
- [ ] Implement routes from evidence/dispute
- [ ] Remove `api-evidence` and `api-dispute` apps
- [ ] Remove python related packages (e.g. `nx-fastapi`) from package.json
- [ ] Clean up features that are redundant/unnecessary, e.g. event interface generation

#### Notes

It might be nice to refactor the blockchain watcher to reuse the same db pod, with a different postgres database.

**Comment by solomondefi-dev** [comment]
@apolkingg8 A few of these tasks can be done in parallel, so let's try to break them down into implementation issues! Usually we don't reference an "epic" issue directly in a commit. I will create a few as an example.
