### ISSUE TITLE
Implement watcher

### ISSUE THREAD

**Issue by apolkingg8** [SolomonDefi/solomon-monorepo#75]
Since the watcher is still in the early stage, I create this issue to collect the user story and todos.

* As a developer, I want the watcher can watch blockchain.
* As a developer, I want the watcher can be tested.
* As a developer, I want the watcher can be reused in different ways.
* As a developer, I want the watcher can handle service offline and avoid rescan all blocks. 
  * #70
* As a developer, I want the watcher can be configured by environment variables. 
  * #1
* As a user, I want the service can mail me when events happened.

**Comment by apolkingg8** [comment]
```
"resolutions": {
  "typechain": "5.1.2",
  "@typechain/ethers-v5": "7.1.2",
  "@typechain/hardhat": "2.3.0"
},
```
It's an unknown issue about `typechain` version resolve. Ref: https://github.com/dethcrypto/TypeChain/issues/401

**Comment by solomondefi-dev** [comment]
> ```
> "resolutions": {
>   "typechain": "5.1.2",
>   "@typechain/ethers-v5": "7.1.2",
>   "@typechain/hardhat": "2.3.0"
> },
> ```
> 
> It's an unknown issue about `typechain` version resolve. Ref: [dethcrypto/TypeChain#401](https://github.com/dethcrypto/TypeChain/issues/401)

Interesting, usually I don't see this kind of problem when using PNPM. Maybe we can create an icebox issue for tracking typechain version.

**Comment by apolkingg8** [comment]
About the test, I think it should be split into two parts: Hardhat (contract) / Jest (event process). So I won't launch a local server (like ganache) to test eth contracts in Jest. I'll mock the contract and test the event process method only.

**Comment by solomondefi-dev** [comment]
Yes, the "Nx way" of doing this is to have unit tests alongside the app code, e.g. `feature/xxx.ts` and `feature/xxx.spec.ts`. Then, we have a separate app for e2e testing, e.g. `apps/blockchain-watcher-e2e`, which only has e2e tests.

**Comment by beefho67** [comment]
> @apolkingg8 Please create a separate issue to record the first thing to be done for the watcher and put the issue into sprint. Thank you.

Hi @apolkingg8 , per our discussion. These are the additional steps we probably need for the epic

- [ ] Migrate contract into Nx project

- [ ] Remove existing dummy contract

- [ ] Add real contract to watcher

- [ ] Test the watcher can work with contract

Please let me know if any of these need to treated as a separate issue. Thanks.
